#ifndef QTHEADERFILES_H
#define QTHEADERFILES_H
#include <QWidget>
#include <QMainWindow>
#include <QDialog>
#include <QApplication>
#include <QPushButton>
#include <QLabel>
#include <QLineEdit>
#include <QCheckBox>
#include <QRadioButton>
#include <QComboBox>
#include <QListWidget>
#include <QTableWidget>
#include <QTreeWidget>
#include <QTabWidget>
#include <QGroupBox>
#include <QStackedWidget>
#include <QScrollArea>
#include <QMessageBox>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QGridLayout>
#include <QFormLayout>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QSlider>
#include <QDial>
#include <QTextEdit>
#include <QPlainTextEdit>
#include <QTableView>
#include <QTreeView>
#include <QListView>
#include <QStandardItemModel>
#include <QPainter>
#include <QPixmap>
#include <QBitmap>
#include <QImage>
#include <QColor>
#include <QFont>
#include <QTimer>
#include <QEvent>
#include <QMenu>
#include <QMenuBar>
#include <QToolBar>
#include <QStatusBar>
#include <QAction>
#include <QFileDialog>
#include <QFile>
#include <QDir>
#include <QSettings>
#include <QClipboard>
#include <QObject>
#include <QString>
#include <QByteArray>
#include <QVariant>
#include <QVector>
#include <QList>
#include <QMap>
#include <QDebug>
#include <QThread>
#include <QMutex>
#include <vector>
#include <array>
#include <deque>
#include <list>
#include <stack>
#include <queue>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <string>
#include <sstream>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <iterator>
#include <functional>
#include <memory>    // smart pointers
#include <utility>   // pair, move, swap
#include <cmath>
#include <limits>
#include <cstdlib>
#include <thread>
#include <mutex>
#include <atomic>
#include <condition_variable>
#include <future>
#endif // QTHEADERFILES_H
